# src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  cloud:
    gateway:
      routes:
        # Auth Service Routes
        - id: auth-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/auth/**

        # User Service Routes
        - id: user-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/users/**

        # Wallet Service Routes
        - id: wallet-service
          uri: http://wallet-service:8092
          predicates:
            - Path=/api/v1/wallets/**

        # Transaction Service Routes
        - id: transaction-service
          uri: http://transaction-service:8093
          predicates:
            - Path=/api/v1/transactions/**

# Logging for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: ${JWT_SECRET:cb9AvXO/RFYa78qgN4G3TCxZ0gxsqgPcCmF9Oq4G9P7V5koI9LW1YaoxrsNhs7rP}
  expiration: 3600000