# src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service
          uri: http://user-service:8091
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2  # Removes /api/users from the path

        # Wallet Service Routes
        - id: wallet-service
          uri: http://wallet-service:8092
          predicates:
            - Path=/api/wallets/**
          filters:
            - StripPrefix=2  # Removes /api/wallets from the path

        # Transaction Service Routes
        - id: transaction-service
          uri: http://transaction-service:8093
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=2  # Removes /api/transactions from the path

# Logging for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG