spring:
  application:
    name: transaction-service
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5433/users_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
  data:
    redis:
      host: localhost
      port: 6379
      database: 1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${TRANSACTION_SERVICE_PORT:8093}

wallet:
  service:
    url: ${WALLET_SERVICE_PORT:localhost:8092}

user:
  service:
    url: ${USER_SERVICE_PORT:8091}

psp:
  flutterwave:
    url: https://api.flutterwave.com
    secret-key: ${FLUTTERWAVE_SECRET_KEY:FLWSECK_TEST-b81dfb98d3a5fc60d0d0d9fa851fa0c1-X}
    encryption-key: ${FLUTTERWAVE_ENCRYPTION_KEY:FLWSECK_TESTcd554fda5816}