spring:
  profiles:
    active: dev

  application:
    name: wallet-service

  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5433/users_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

server:
  port: ${WALLET_SERVICE_PORT:8092}

user:
  service:
    url: ${USER_SERVICE_PORT:http://localhost:8091}
